# Generated by Django 4.2.20 on 2025-04-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_uploadedimage_result_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video', models.FileField(upload_to='uploads/videos/')),
                ('result_video', models.FileField(blank=True, null=True, upload_to='results/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='frame_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/images/'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.uploadedvideo'),
        ),
    ]
