# Generated by Django 4.2.20 on 2025-04-06 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_uploadedvideo_remove_detectionresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
