# Generated by Django 4.2.20 on 2025-04-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_detectionresult_created_at_alter_uploadedimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionresult',
            name='frame_time',
        ),
    ]
